### ISSUE TITLE
OpenAI Errors

### ISSUE THREAD

**Issue by ghost** [jorgik1/youtuber_ai_chatbot#1]
Hi @jorgik1, 

Are you still using OpenAI in this? I see some references to it, but also saw a couple OSS models like falcon in the code. 

-- 
Faced issues with openai rate limiting, so would recommend wrapping your call with `reliableGPT`

```
from reliablegpt import reliableGPT
openai.ChatCompletion.create = reliableGPT(openai.ChatCompletion.create, ...)
```

Source: https://github.com/BerriAI/reliableGPT

**Comment by jorgik1** [comment]
Ok thanks
